algoritmo "Estoque"
// Função : Calcular o valor total da peça
// Autor : Guilherme Pechtoll
// Data : 04/03/2020
// Seção de Declarações 
var
valor : real
qtde: inteiro
vt: real
inicio
escreval("Qual a quantidade de peças?")
leia(qtde)
escreval("Qual o valor de cada peça?")
leia(valor)

vt <- valor*qtde

escreval("O valor total das peças do estoque é: R$", vt)









fimalgoritmo
