algoritmo "Estoquemedio"
// Função : Calcular o valor do estoque medio
// Autor : Guilherme Pechtoll
// Data : 04/03/2020
// Seção de Declarações 
var
esqmax : real
esqmin: inteiro
esqmedio: real
inicio
escreval("Qual a quantidade maxima do estoque de peças?")
leia(esqmax)
escreval("Qual a quantidade minima do estoque de peças?")
leia(esqmin)

esqmedio <- (esqmax+esqmin)/2

escreval("O Estoque medio de peças é de: ", esqmedio)









fimalgoritmo
