algoritmo "retangulo"
// Função : Calcular o perimetro do retângulo
// Autor : Guilherme Pechtoll
// Data : 12/02/2020
// Seção de Declarações 
var
b: real
a: real
ra: real
rp: real
inicio
escreva("Digite a altura do retângulo: ")
leia(a)
escreva("Digite a base do retângulo: ")
leia(b)

ra <- (b *a)/2

rp <- (b *2 + a*2)

escreva("a área do retângulo é : ",ra)

escreva("o perimetro do retângulo é : ",rp)




fimalgoritmo
