algoritmo "cotação"
// Função :
// Autor :
// Data : 11/03/2020
// Seção de Declarações 
var
n1, n2, n3, n4, resultado: real
inicio
escreval("Digite o primeiro numero :")
leia(n1)
escreval("Digite o segundo numero :")
leia(n2)
escreval("Digite o terceiro numero :")
leia(n3)
escreval("Digite o quarto numero :")
leia(n4)

resultado <- n1^2+n2^2+n3^2+n4^2

escreval("O resultado da potencialização é :",resultado)

fimalgoritmo
